workflows:
  android-arm64:
    name: Android ARM64 Build
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17
      groups:
        - secrets  # this loads your Supabase URL + anon key from Codemagic UI env vars

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      # --- NEW: ICON GENERATOR STEP ---
      # This ensures the custom icon is generated fresh for every build
      - name: Generate App Icons
        script: |
          echo "🔮 Generating App Icons..."
          dart run flutter_launcher_icons

      - name: Build Android APK (ARM64 only)
        script: |
          flutter build apk --release --target-platform android-arm64

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - your_rudeboyemyres@gmail.com
        notify:
          success: true
          failure: true
