-- 1. Create Blocks Table
CREATE TABLE IF NOT EXISTS user_blocks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blocker_id uuid REFERENCES auth.users NOT NULL,
  blocked_id uuid REFERENCES auth.users NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(blocker_id, blocked_id)
);

-- 2. Create Reports Table
CREATE TABLE IF NOT EXISTS reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id uuid REFERENCES auth.users NOT NULL,
  reported_user_id uuid REFERENCES auth.users, -- Nullable (if reporting video)
  -- FIX: Changed from bigint to uuid to match your videos table
  reported_video_id uuid REFERENCES videos(id), 
  reason text NOT NULL,
  status text DEFAULT 'pending', -- pending, reviewed, resolved
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. RLS Policies (Security)
ALTER TABLE user_blocks ENABLE ROW LEVEL SECURITY;

-- Drop policies if they exist to avoid errors on re-run (optional but safe)
DROP POLICY IF EXISTS "Users can block others" ON user_blocks;
DROP POLICY IF EXISTS "Users can view their blocks" ON user_blocks;
DROP POLICY IF EXISTS "Users can unblock" ON user_blocks;
DROP POLICY IF EXISTS "Users can create reports" ON reports;

CREATE POLICY "Users can block others" ON user_blocks FOR INSERT WITH CHECK (auth.uid() = blocker_id);
CREATE POLICY "Users can view their blocks" ON user_blocks FOR SELECT USING (auth.uid() = blocker_id);
CREATE POLICY "Users can unblock" ON user_blocks FOR DELETE USING (auth.uid() = blocker_id);

ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can create reports" ON reports FOR INSERT WITH CHECK (auth.uid() = reporter_id);
